version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_CONN_MAX_AGE:

  web:
    build: .
    command: bash -c "python manage.py migrate &&
             python manage.py create_superuser --username=admin --password=admin --email=admin@g.com &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app_agg
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DEBUG:
      SECRET_KEY:

volumes:
  postgres_data: