version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_CONN_MAX_AGE:
      POSTGRES_PORT:
    env_file:
      - ./AppAggregator/.env

  web:
    env_file:
      - ./AppAggregator/.env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app_agg
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG:
      SECRET_KEY: