version: '3'

services:
  web:
    container_name: app_agg_web
    build: .
    command: bash -c "python manage.py migrate &&
      python manage.py create_superuser --username=admin --password=admin --email=admin@g.com &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG:
      SECRET_KEY:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_CONN_MAX_AGE:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 15s
      retries: 2

volumes:
  postgres_data: