# Generated by Django 5.0.1 on 2024-01-16 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPurchasedApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_apps', to='app_aggregator.appdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
