# Generated by Django 5.0.1 on 2024-01-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aggregator', '0002_userpurchasedapps'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchasedapps',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
